#spring.datasource.url=jdbc:mysql://localhost:3306/my_db
#spring.datasource.name=Max
#spring.datasource.password=Maxroot8
#$ docker run --name some-postgres -e POSTGRES_PASSWORD=postgres -p 5433:5432 -d postgres

spring:
  datasource:
    hikari:
      username: postgres
      password: postgres
    #    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my_db
    url: jdbc:postgresql://localhost:5433/postgres
    name: postgres
    password: postgres


  jpa:
    properties.hibernate:
        show_sql: true
        format_sql: true
#        hbm2ddl.auto: validate