#spring.datasource.url=jdbc:mysql://localhost:3306/my_db
#spring.datasource.name=Max
#spring.datasource.password=Maxroot8


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    name: postgres
    password: postgres

      # for Docker
    # url: jdbc:postgresql://localhost:5433/postgres



  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      #        hbm2ddl.auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 456910870245-2558jpa2glr33kpgl5tuv5taupiiqknu.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile


  mail:
    host: smtp.gmail.com
    port: 587
    username: maxfortest91@gmail.com
    password: mfblvqqnvtwvbvit
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com

